export const CONST_QUESTION_LIST = {
  listOfMultipleAnswerTypeMcq: [
    {
      questionId: "e5np83",
      questionSequenceNumber: 2,
      questionDifficulty: "EASY",
      questionType: "MCQ_MULTIPLE",
      questionTag: "Yo",
      questionCreationTimestamp: "2020-09-09T13:34:37.3221172",
      questionUpdateTimestamp: "2020-09-09T13:34:37.3221172",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Phy",
      questionText: "What is an ohm?",
      options: ["DCS", "SS", "gg", "ww"],
      answers: ["DCS", "SS"],
    },
    {
      questionId: "e5np09",
      questionSequenceNumber: 4,
      questionDifficulty: "EASY",
      questionType: "MCQ_MULTIPLE",
      questionTag: "Yo",
      questionCreationTimestamp: "2020-09-09T13:34:37.3221172",
      questionUpdateTimestamp: "2020-09-09T13:34:37.3221172",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Phy",
      questionText: "What is an ohm?",
      options: ["DCS", "SS", "gg", "ww"],
      answers: ["DCS", "SS"],
    },
    {
      questionId: "e5bc09",
      questionSequenceNumber: 5,
      questionDifficulty: "EASY",
      questionType: "MCQ_MULTIPLE",
      questionTag: "Yo",
      questionCreationTimestamp: "2020-09-09T13:34:37.3221172",
      questionUpdateTimestamp: "2020-09-09T13:34:37.3221172",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Phy",
      questionText: "What is an ohm?",
      options: ["DCS", "SS", "gg", "ww"],
      answers: ["DCS", "SS"],
    },
  ],
  listOfSingleAnswerTypeMcq: [
    {
      questionId: "zs1i2k",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "u2iqae",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "u2iqqe",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "u2iqoe",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "u2iqje",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "u2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "p2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "f2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "d2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "a2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "l2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "v2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "s2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "j2iqle",
      questionSequenceNumber: 1,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
    {
      questionId: "bc1i2k",
      questionSequenceNumber: 3,
      questionDifficulty: "EASY",
      questionType: "MCQ_SINGLE",
      questionTag: "Yo",
      questionCreationTimestamp: "1600158956",
      questionUpdateTimestamp: "1600158956",
      questionMarks: 100.0,
      questionNegativeMarks: -9.0,
      class_: 10,
      questionSubject: "Chem",
      questionText: "what is sn2 reaction?",
      options: ["DCS", "SS", "gg", "ww"],
      answer: "DCS",
    },
  ],
};

export const QUESTION_TYPES = {
  MCQ_SINGLE: "MCQ_SINGLE",
  MCQ_MULTIPLE: "MCQ_MULTIPLE",
};
